# Generated by Django 6.0.8 on 2026-09-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Texto exibido no link de navegação.', max_length=100, verbose_name='Título')),
                ('position', models.CharField(choices=[('header', 'Header (menu superior)'), ('footer', 'Footer (menu institucional)')], default='header', help_text='Onde este item deve aparecer: menu superior (header) ou rodapé (footer).', max_length=20, verbose_name='Posição')),
                ('link_url', models.CharField(blank=True, help_text="URL externa ou caminho arbitrário. Usada apenas se 'Página' estiver vazia.", max_length=500, verbose_name='URL externa')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro).', verbose_name='Ordem')),
                ('page', models.ForeignKey(blank=True, help_text='Página interna do site. Se preenchida, tem prioridade sobre a URL externa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Item de Navegação',
                'verbose_name_plural': 'Itens de Navegação',
                'ordering': ['position', 'sort_order', 'title'],
            },
        ),
    ]
