# Generated by Django 6.0.8 on 2026-09-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, este item vira um submenu do item pai, permitindo hierarquia multinível.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationitem', verbose_name='Item Pai (Submenu de)'),
        ),
    ]
