# Generated by Django 6.0.5 on 2026-08-24 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicativos', '0002_initial'),
        ('conteudos', '0001_initial'),
        ('interacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoconteudo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='aplicativo',
            field=models.ForeignKey(blank=True, help_text='Aplicativo educacional comentado (um dos dois deve ser preenchido).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='aplicativos.aplicativoeducacionalpage', verbose_name='aplicativo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='conteudo',
            field=models.ForeignKey(blank=True, help_text='Conteúdo educacional comentado (um dos dois deve ser preenchido).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='conteudos.conteudopage', verbose_name='conteúdo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Autor do comentário. SET_NULL ao excluir conta (anonimiza).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='favoritoconteudo',
            name='conteudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='conteudos.conteudopage', verbose_name='conteúdo'),
        ),
        migrations.AddField(
            model_name='favoritoconteudo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='like',
            name='aplicativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='aplicativos.aplicativoeducacionalpage', verbose_name='aplicativo'),
        ),
        migrations.AddField(
            model_name='like',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='conteudos.conteudopage', verbose_name='conteúdo'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddIndex(
            model_name='avaliacaoconteudo',
            index=models.Index(fields=['conteudo', '-criado_em'], name='interacoes__conteud_67b2e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoconteudo',
            unique_together={('user', 'conteudo')},
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['conteudo', 'is_approved', '-criado_em'], name='interacoes__conteud_dfebad_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['aplicativo', 'is_approved', '-criado_em'], name='interacoes__aplicat_67236f_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritoconteudo',
            index=models.Index(fields=['user', '-criado_em'], name='interacoes__user_id_8b2e6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritoconteudo',
            unique_together={('user', 'conteudo')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['conteudo', '-criado_em'], name='interacoes__conteud_e9b116_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['aplicativo', '-criado_em'], name='interacoes__aplicat_ef00b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'aplicativo'), ('user', 'conteudo')},
        ),
    ]
