# Generated by Django 6.0.5 on 2026-08-24 14:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('super-admin', 'Super Admin'), ('admin', 'Admin'), ('coordenador', 'Coordenador'), ('editor', 'Editor'), ('convidado', 'Convidado')], max_length=20, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de hierarquia (menor = mais privilégios).', verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papéis',
                'ordering': ['ordem', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Já existe um usuário com este username.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_ apenas.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um usuário com este e-mail.'}, max_length=254, unique=True, verbose_name='e-mail')),
                ('verified', models.BooleanField(default=False, help_text='E-mail verificado via token enviado no cadastro.', verbose_name='verificado')),
                ('verification_token', models.CharField(blank=True, help_text='Token para verificação de e-mail. Expira após uso.', max_length=100, verbose_name='token de verificação')),
                ('verification_token_created_at', models.DateTimeField(blank=True, help_text='Timestamp de criação do token (para expiração).', null=True, verbose_name='token criado em')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Metadados flexíveis (ex: preferências de UI, configurações de notificação).', verbose_name='opções extras')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp de exclusão lógica (soft delete).', null=True, verbose_name='excluído em')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuário que realizou a exclusão lógica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL, verbose_name='excluído por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuarios_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(help_text='Papel do usuário no sistema (define permissões).', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='usuarios.role', verbose_name='papel')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
