# Generated by Django 6.0.5 on 2026-08-24 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('canais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='canais.canalpage', verbose_name='canal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_vinculados', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'vínculo usuário-canal',
                'verbose_name_plural': 'vínculos usuário-canal',
                'ordering': ['-criado_em'],
                'unique_together': {('user', 'canal')},
            },
        ),
    ]