# Generated by Django 6.0.5 on 2026-08-24 14:26

from django.db import migrations


def create_default_roles(apps, schema_editor):
    Role = apps.get_model("usuarios", "Role")
    roles_data = [
        {"slug": "super-admin", "name": "Super Admin", "description": "Acesso irrestrito ao sistema.", "ordem": 1},
        {"slug": "admin", "name": "Admin", "description": "Quase irrestrito, abaixo de super-admin em ações destrutivas.", "ordem": 2},
        {"slug": "coordenador", "name": "Coordenador", "description": "Pode criar/editar conteúdo, aprovar, gerenciar tags/playlists/contato.", "ordem": 3},
        {"slug": "editor", "name": "Editor", "description": "Papel reservado (sem permissões especiais implementadas no legado).", "ordem": 4},
        {"slug": "convidado", "name": "Convidado", "description": "Papel padrão de novo cadastro (self-registration).", "ordem": 5},
    ]
    for data in roles_data:
        Role.objects.get_or_create(slug=data["slug"], defaults=data)


def remove_default_roles(apps, schema_editor):
    Role = apps.get_model("usuarios", "Role")
    Role.objects.filter(slug__in=["super-admin", "admin", "coordenador", "editor", "convidado"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usercanal"),
    ]

    operations = [
        migrations.RunPython(create_default_roles, remove_default_roles),
    ]
