# Generated by Django 6.0.5 on 2026-08-24 13:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Título personalizado para Facebook, Instagram e WhatsApp. Se vazio, usa o título da página.', max_length=100, verbose_name='Título Redes Sociais')),
                ('og_description', models.TextField(blank=True, help_text='Descrição curta para compartilhamento. Se vazio, usa a descrição de busca (SEO).', verbose_name='Descrição Redes Sociais')),
                ('name', models.CharField(help_text="Nome do canal (ex: 'TV Anísio Teixeira', 'Recursos Educacionais').", max_length=150, unique=True, verbose_name='Nome')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Descrição rica do canal para exibição na página do canal.', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Canal ativo e visível na navegação. Desativar para tirar de circulação sem apagar conteúdo histórico.', verbose_name='Ativo')),
                ('token', models.CharField(blank=True, help_text='Credencial de conexão com API externa (YouTube, Spotify, WordPress, Colaborativus, etc.). NUNCA expor em API pública. Usar campo criptografado em produção.', max_length=500, verbose_name='Token de API')),
                ('options', models.JSONField(blank=True, default=dict, help_text="JSON para configurações flexíveis (ex: {'cor': '#FF5733'}).", verbose_name='Opções extras')),
                ('categorias_componente_permitidas', models.ManyToManyField(blank=True, help_text='Restringe quais categorias de componente curricular são relevantes para este canal.', related_name='canais_permitidos', to='curriculo.curricularcomponentcategory', verbose_name='Categorias de componente curricular permitidas')),
                ('og_image', models.ForeignKey(blank=True, help_text='Imagem que aparecerá no card de compartilhamento (Recomendado: 1200x630px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Redes Sociais')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'ordering': ['name'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
