# Generated by Django 6.0.5 on 2026-08-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canais', '0001_initial'),
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalpage',
            name='tipos_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Restringe quais tipos de mídia são relevantes/exibidos neste canal. Regra de negócio ativa (filtro), não só decoração.', related_name='canais_permitidos', to='conteudos.tipo', verbose_name='Tipos de conteúdo permitidos'),
        ),
    ]
