# Generated by Django 6.0.8 on 2026-09-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canais', '0002_canalpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalpage',
            name='categorias_componente_permitidas',
        ),
    ]
