# Generated by Django 6.0.5 on 2026-05-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Descrição curta para compartilhamento. Se vazio, usa a descrição de busca (SEO).', verbose_name='Descrição Redes Sociais'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Imagem que aparecerá no card de compartilhamento (Recomendado: 1200x630px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Redes Sociais'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Título personalizado para Facebook, Instagram e WhatsApp. Se vazio, usa o título da página.', max_length=100, verbose_name='Título Redes Sociais'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Descrição curta para os resultados de busca.', max_length=255, verbose_name='Descrição SEO'),
        ),
    ]
