# Generated by Django 6.0.5 on 2026-05-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_og_description_homepage_og_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='seo_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_body_class',
            field=models.CharField(blank=True, help_text='Classe CSS opcional aplicada à tag <body>.', max_length=100, verbose_name='Classe CSS do Body'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hide_footer',
            field=models.BooleanField(default=False, verbose_name='Esconder Footer'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hide_header',
            field=models.BooleanField(default=False, verbose_name='Esconder Header'),
        ),
    ]
