# Generated by Django 6.0.5 on 2026-08-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_seo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='custom_body_class',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hide_footer',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hide_header',
        ),
    ]
