# Generated by Django 6.0.5 on 2026-08-24 13:56

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicativoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='aplicativos.aplicativocategory', verbose_name='categoria pai')),
            ],
            options={
                'verbose_name': 'categoria de aplicativo',
                'verbose_name_plural': 'categorias de aplicativos',
                'ordering': ['ordem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AplicativoEducacionalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Título personalizado para Facebook, Instagram e WhatsApp. Se vazio, usa o título da página.', max_length=100, verbose_name='Título Redes Sociais')),
                ('og_description', models.TextField(blank=True, help_text='Descrição curta para compartilhamento. Se vazio, usa a descrição de busca (SEO).', verbose_name='Descrição Redes Sociais')),
                ('url', models.URLField(help_text='URL externa do aplicativo. Será validada se resolve corretamente (DNS/HTTP).', max_length=500, verbose_name='URL do aplicativo')),
                ('description', wagtail.fields.RichTextField(help_text='Mínimo 140 caracteres (validação do legado).', verbose_name='descrição')),
                ('is_featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('qt_access', models.PositiveIntegerField(default=0, editable=False, help_text='Contador iniciado em 0, incrementado a cada acesso.', verbose_name='quantidade de acessos')),
                ('autor', models.ForeignKey(help_text='Usuário que publicou este recurso.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'aplicativo educacional',
                'verbose_name_plural': 'aplicativos educacionais',
            },
            bases=('wagtailcore.page',),
        ),
    ]
