# Generated by Django 6.0.5 on 2026-08-24 13:56

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicativos', '0001_initial'),
        ('canais', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicativoeducacionalpage',
            name='canal',
            field=models.ForeignKey(help_text='Canal ao qual este recurso pertence.', on_delete=django.db.models.deletion.PROTECT, to='canais.canalpage', verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='aplicativoeducacionalpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicativos', to='aplicativos.aplicativocategory', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='aplicativoeducacionalpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Formatos aceitos: jpeg, png, jpg, svg. Tamanho máximo: 1MB.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='imagem/ícone'),
        ),
        migrations.AddField(
            model_name='aplicativoeducacionalpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Imagem que aparecerá no card de compartilhamento (Recomendado: 1200x630px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Redes Sociais'),
        ),
        migrations.AddField(
            model_name='aplicativoeducacionalpage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags para categorização e busca.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
