# Generated by Django 6.0.5 on 2026-08-24 13:56

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canais', '0001_initial'),
        ('curriculo', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('options', models.JSONField(blank=True, default=dict, help_text="JSON com configurações do tipo. Ex: {'formatos': ['mp4', 'webm', 'ogg']}", verbose_name='Opções')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Tipo de Conteúdo',
                'verbose_name_plural': 'Tipos de Conteúdo',
                'ordering': ['ordem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='canais.canalpage', verbose_name='Canal')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='conteudos.categoria', verbose_name='Categoria pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['canal', 'ordem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('url', models.URLField(blank=True, verbose_name='URL da licença')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sublicencas', to='conteudos.licenca', verbose_name='Licença pai')),
            ],
            options={
                'verbose_name': 'Licença',
                'verbose_name_plural': 'Licenças',
                'ordering': ['ordem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConteudoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Título personalizado para Facebook, Instagram e WhatsApp. Se vazio, usa o título da página.', max_length=100, verbose_name='Título Redes Sociais')),
                ('og_description', models.TextField(blank=True, help_text='Descrição curta para compartilhamento. Se vazio, usa a descrição de busca (SEO).', verbose_name='Descrição Redes Sociais')),
                ('arquivo', models.FileField(blank=True, help_text='Arquivo de mídia/documento. Extensão validada conforme o Tipo (RN-L3).', null=True, upload_to='conteudos/arquivos/%Y/%m/', verbose_name='Arquivo')),
                ('authors', models.CharField(blank=True, help_text='Nomes dos autores/criadores do recurso (diferente do autor publicador).', max_length=500, verbose_name='Autores do conteúdo')),
                ('source', models.URLField(blank=True, help_text='URL da fonte original do conteúdo, se aplicável.', verbose_name='Fonte original')),
                ('options', models.JSONField(blank=True, default=dict, help_text='JSON para dados flexíveis (acessibilidade, site associado, etc.).', verbose_name='Opções extras')),
                ('is_approved', models.BooleanField(default=False, help_text='Conteúdo aprovado para publicação. Só coordenador+ pode aprovar.', verbose_name='Aprovado')),
                ('is_featured', models.BooleanField(default=False, help_text='Exibir em destaque na home/listagens.', verbose_name='Em destaque')),
                ('is_site', models.BooleanField(default=False, help_text='Marca se o conteúdo é um site associado (legado: is_site).', verbose_name='É site')),
                ('qt_downloads', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantidade de downloads')),
                ('qt_access', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantidade de acessos')),
                ('numero_episodio', models.PositiveSmallIntegerField(blank=True, help_text='Preenchido apenas quando o conteúdo é filho de uma Temporada (app series).', null=True, verbose_name='Número do episódio')),
                ('media_avaliacao', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Atualizado automaticamente via signal. Não usar em filtros/ordenação (RF011).', max_digits=3, verbose_name='Média de avaliação')),
                ('total_avaliacoes', models.PositiveIntegerField(default=0, editable=False, help_text='Atualizado automaticamente via signal.', verbose_name='Total de avaliações')),
                ('autor', models.ForeignKey(help_text='Usuário que publicou este recurso.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('canal', models.ForeignKey(help_text='Canal ao qual este recurso pertence.', on_delete=django.db.models.deletion.PROTECT, to='canais.canalpage', verbose_name='Canal')),
                ('category', models.ForeignKey(help_text='Categoria do conteúdo (árvore escopada por canal).', on_delete=django.db.models.deletion.PROTECT, to='conteudos.categoria', verbose_name='Categoria')),
                ('componentes_curriculares', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Mínimo 1 obrigatório (regra pedagógica RN-L5).', to='curriculo.curricularcomponent', verbose_name='Componentes Curriculares')),
                ('og_image', models.ForeignKey(blank=True, help_text='Imagem que aparecerá no card de compartilhamento (Recomendado: 1200x630px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Redes Sociais')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags para categorização e busca.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('license', models.ForeignKey(blank=True, help_text='Licença de uso (estrutura em árvore tipo Creative Commons).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='conteudos.licenca', verbose_name='Licença')),
                ('tipo', models.ForeignKey(help_text='Define o player/template e valida extensões de upload.', on_delete=django.db.models.deletion.PROTECT, to='conteudos.tipo', verbose_name='Tipo de mídia')),
            ],
            options={
                'verbose_name': 'Conteúdo Educacional',
                'verbose_name_plural': 'Conteúdos Educacionais',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('slug', 'canal'), name='unique_categoria_slug_per_canal'),
        ),
    ]
