# Generated by Django 6.0.8 on 2026-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais', '0002_initial'),
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaConteudo',
        ),
        migrations.AlterModelOptions(
            name='categoriaconteudo',
            options={'ordering': ['canal', 'ordem', 'name'], 'verbose_name': 'Categoria de Conteúdo', 'verbose_name_plural': 'Categorias de Conteúdo'},
        ),
        migrations.RemoveConstraint(
            model_name='categoriaconteudo',
            name='unique_categoria_slug_per_canal',
        ),
        migrations.AddConstraint(
            model_name='categoriaconteudo',
            constraint=models.UniqueConstraint(fields=('slug', 'canal'), name='unique_categoriaconteudo_slug_per_canal'),
        ),
    ]
