# Generated by Django 6.0.8 on 2026-09-02 19:41

import django.db.models.deletion
from django.db import migrations, models


# ---------------------------------------------------------------------------
# Backfill do mecanismo de exibição a partir do slug do `tipo` associado.
#
# A decisão arquitetural (CONTEXT.MD seção 3) separa a taxonomia pedagógica
# (`tipo`) do formato técnico de renderização (`mecanismo_exibicao`). Para
# registros existentes, derivamos o mecanismo a partir do slug do tipo:
#   - video        -> video
#   - audio        -> audio
#   - documento    -> documento_pdf
#   - apresentacao -> apresentacao
#   - demais       -> link_externo (fallback neutro seguro)
# ---------------------------------------------------------------------------
MECANISMO_VIDEO = "video"
MECANISMO_AUDIO = "audio"
MECANISMO_DOCUMENTO_PDF = "documento_pdf"
MECANISMO_APRESENTACAO = "apresentacao"
MECANISMO_LINK_EXTERNO = "link_externo"

# Mapeamento slug do tipo -> mecanismo de exibição
SLUG_TIPO_PARA_MECANISMO = {
    "video": MECANISMO_VIDEO,
    "audio": MECANISMO_AUDIO,
    "documento": MECANISMO_DOCUMENTO_PDF,
    "apresentacao": MECANISMO_APRESENTACAO,
}


def _mecanismo_para_slug_tipo(slug_tipo):
    """Retorna o mecanismo de exibição derivado do slug do tipo (com fallback)."""
    return SLUG_TIPO_PARA_MECANISMO.get(slug_tipo, MECANISMO_LINK_EXTERNO)


def forwards(apps, schema_editor):
    """Backfill idempotente do mecanismo_exibicao a partir do slug do tipo."""
    ConteudoPage = apps.get_model("conteudos", "ConteudoPage")
    Tipo = apps.get_model("conteudos", "Tipo")

    # Mapa slug -> mecanismo para evitar N+1 queries
    slug_para_mecanismo = {
        t.slug: _mecanismo_para_slug_tipo(t.slug)
        for t in Tipo.objects.all()
    }

    for conteudo in ConteudoPage.objects.select_related("tipo").iterator():
        slug_tipo = conteudo.tipo.slug if conteudo.tipo else None
        mecanismo = slug_para_mecanismo.get(slug_tipo, MECANISMO_LINK_EXTERNO)
        if conteudo.mecanismo_exibicao != mecanismo:
            conteudo.mecanismo_exibicao = mecanismo
            conteudo.save(update_fields=["mecanismo_exibicao"])


def backwards(apps, schema_editor):
    """Reversão: restaura o default neutro (link_externo) para todos os registros."""
    ConteudoPage = apps.get_model("conteudos", "ConteudoPage")
    ConteudoPage.objects.update(mecanismo_exibicao=MECANISMO_LINK_EXTERNO)


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0002_rename_categoria_categoriaconteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudopage',
            name='mecanismo_exibicao',
            field=models.CharField(choices=[('video', 'Vídeo — Player responsivo 16:9.'), ('audio', 'Áudio — Player de áudio nativo estilizado.'), ('documento_pdf', 'Documento PDF — Visualizador embutido ou download seguro de PDF.'), ('apresentacao', 'Apresentação — Visualizador/download de apresentação.'), ('download_binario', 'Download binário — Download seguro de pacotes/executáveis (.zip, .rar, .exe).'), ('link_externo', 'Link externo — Link externo seguro (noopener noreferrer).'), ('animacao_externa', 'Animação externa — iframe protegido para animações/sites externos.')], default='link_externo', help_text="Formato técnico de renderização (distinto da categoria pedagógica 'tipo'). Determina o player/visualizador usado na exibição do conteúdo.", max_length=30, verbose_name='Mecanismo de Exibição'),
        ),
        migrations.AlterField(
            model_name='conteudopage',
            name='tipo',
            field=models.ForeignKey(help_text='Categoria pedagógica do conteúdo (usada em filtros de busca e currículo).', on_delete=django.db.models.deletion.PROTECT, to='conteudos.tipo', verbose_name='Tipo de mídia'),
        ),
        migrations.RunPython(
            code=forwards,
            reverse_code=backwards,
        ),
    ]
