# Generated by Django 6.0.8 on 2026-09-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0003_conteudopage_mecanismo_exibicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudopage',
            name='source',
            field=models.URLField(blank=True, help_text='URL externa (MODO B) usada pelos mecanismos link_externo e animacao_externa. Aceita a URL do navegador (ex: youtube.com/watch?v=ID, youtu.be/ID, vimeo.com/ID): a resolução via oEmbed é feita no template com {% embed %} / get_embed() — nunca passar a URL direto para <iframe src>.', verbose_name='URL de mídia externa'),
        ),
    ]
