# Generated by Django 6.0.5 on 2026-08-24 13:56

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canais', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_title', models.CharField(blank=True, help_text='Título personalizado para Facebook, Instagram e WhatsApp. Se vazio, usa o título da página.', max_length=100, verbose_name='Título Redes Sociais')),
                ('og_description', models.TextField(blank=True, help_text='Descrição curta para compartilhamento. Se vazio, usa a descrição de busca (SEO).', verbose_name='Descrição Redes Sociais')),
                ('sinopse', models.TextField(blank=True, help_text='Descrição/sinopse da série para exibição na página da série.', verbose_name='Sinopse')),
                ('autor', models.ForeignKey(help_text='Usuário que publicou este recurso.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('canal', models.ForeignKey(blank=True, help_text='Séries são independentes de canal. Este campo não deve ser preenchido.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='canais.canalpage', verbose_name='Canal (não usado para Séries)')),
                ('capa', models.ForeignKey(blank=True, help_text='Imagem de capa/banner da série (recomendado: 16:9).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa da Série')),
                ('og_image', models.ForeignKey(blank=True, help_text='Imagem que aparecerá no card de compartilhamento (Recomendado: 1200x630px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Redes Sociais')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags para categorização e busca.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('numero', models.PositiveSmallIntegerField(help_text='Número ordinal da temporada (1, 2, 3...).', verbose_name='Número da Temporada')),
                ('sinopse', models.TextField(blank=True, help_text='Descrição opcional da temporada.', verbose_name='Sinopse da Temporada')),
                ('capa', models.ForeignKey(blank=True, help_text='Imagem de capa da temporada (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Capa da Temporada')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['numero'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
