# Generated by Django 6.0.5 on 2026-08-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurricularComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Agrupador de disciplinas (ex: 'Ciências da Natureza', 'Linguagens').", max_length=150, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Componente Curricular',
                'verbose_name_plural': 'Categorias de Componentes Curriculares',
                'ordering': ['ordem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ex: '1º ano do Ensino Médio', '5º ano do Ensino Fundamental I'.", max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador único para URLs e APIs.', max_length=100, unique=True, verbose_name='Slug')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição em listas/selects.', verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Nível de Ensino',
                'verbose_name_plural': 'Níveis de Ensino',
                'ordering': ['ordem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurricularComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome do componente (ex: 'Matemática — 1º ano', 'Língua Portuguesa — 5º ano').", max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descrição pedagógica do componente (opcional).', verbose_name='Descrição')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(help_text="Agrupador disciplinar (ex: 'Matemática', 'Ciências da Natureza').", on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='curriculo.curricularcomponentcategory', verbose_name='Categoria')),
                ('nivel', models.ForeignKey(help_text="Nível ao qual este componente pertence (ex: '1º ano do Ensino Médio').", on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='curriculo.nivelensino', verbose_name='Nível de Ensino')),
            ],
            options={
                'verbose_name': 'Componente Curricular',
                'verbose_name_plural': 'Componentes Curriculares',
                'ordering': ['nivel__ordem', 'category__ordem', 'ordem', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'nivel', 'category'), name='unique_componente_per_nivel_categoria')],
            },
        ),
    ]
