# Generated by Django 6.0.8 on 2026-08-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curricularcomponentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoria pai para estrutura hierárquica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='curriculo.curricularcomponentcategory', verbose_name='Categoria Pai'),
        ),
    ]
